export const P_1 = 'Bonjour je suis'
export const P_2 = 'NOUGLOZEH Gerard'
export const P_3 = 'developpeur full stack'
export const P_4 = 'Recherche active non '
export const P_5 = 'Toulouse, France'
export const P_6 = 'Développeur full stack chez Atos'
export const TITRE_RESUME = "Accueil"
export const TITRE_RESUME_1 = "Resumé"
export const TITRE_EXP = "Experiences"
export const TITRE_SKILL = "Compétences"
export const TITRE_LANG = "Loisires et Langues"
export const TITRE_FORMATION = "Formations"
export const TITRE_CONTACT = "Contact"
export const TEST = "Test"
export const TTTRE = 'Cv NOUGLOZEH Gerard'
export const TTTRE_Legende = 'Légende'
